# -*- coding: utf-8 -*-
"""kevin parsing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rNDcLJ7kwzJJ3yRc8-6L-r2wq_hVjvgP
"""

!pip install python-docx
from docx import Document

"""the function that parses words in bold

///

функция, парсящая выделеннные жирным слова
"""

def get_bold_text(document):
  """
  extracts bold text from a DOCX document.
  :param input: a docx file with kev's text
  :return: a list of bold text strings found in the document, normalized
  """
  bold_text = []
  for paragraph in document.paragraphs:
    for word in paragraph.runs:
      if word.bold:
        bold_text.append(word.text)
  return bold_text

"""normalization: deleting duples, capilazing

///


нормализация: удаление дубликатов, капитализация
"""

def final_normalizing(input):
  """
  deletes duplicates and capitilizes words
  :param input: '1', '0,', 'abggah', 'aur', '1', 'twuht', 'aur', 'TwuhT'
  :return: '1', '0,', 'Abggah', 'Aur', 'Twuht'
  """
  result = []
  for elem in input:
    if elem.capitalize() not in result:
      result.append(elem.capitalize())
  return result

"""parsing and enacting functions. argument of Document is, in this case of Google Collab, the address of the parsed file in Google Drive. It can be copied in rightclick.

///

парсинг и применение функций. аргумент Document() -- адрес файла в гугл драйве. его можно скопировать райткликом.
"""

file_path = '/content/drive/MyDrive/Colab Notebooks/kevin\'s texts.docx' #любое имя фай
document = Document(file_path)
bold_words = get_bold_text(document)
normalized_bolds = final_normalizing([word for word in bold_words if word.isalpha()])
words_count = len(normalized_bolds)

"""printing a final result, enumerated

///

печать пронумерованного конечного результата
"""

for index, word in enumerate(normalized_bolds, 1):
  print(f'{index}. {word}')
print(f'Here are {words_count} parsed words.')
